name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn clean install -PUI
#          run: mvn clean install -PUI
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: 111111111222/test_repo
          tags: latest
#          tags: ${{github.run_number}}
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://45.136.180.252:8080"
          user: "admin"
          token: "112ee0a1cb33c72524dd27ae0583c6543d"
          job: "test"